---
- name: Install python3 on Ubuntu
  become: yes
  raw: DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3
  changed_when: false
  failed_when: false
  register: apt_install_result
  until: apt_install_result is succeeded
