---
- name: Install python3 on CentOS 7
  become: yes
  raw: yum -q install -y python3 python3-libselinux
  changed_when: false
  failed_when: false
  register: yum_install_result
  until: (yum_install_result is succeeded) and ('Failed' not in yum_install_result.stdout)
  when: '''VERSION_ID="7"'' in os_release_lines'

- name: Install python3 on Centos 8
  become: yes
  raw: dnf -q install -y python3 python3-libselinux
  changed_when: false
  failed_when: false
  register: dnf_install_result
  until: (dnf_install_result is succeeded) and ('Failed' not in dnf_install_result.stdout)
  when: '''PLATFORM_ID="platform:el8"'' in os_release_lines'
