---
- name: Verify python2 on Centos 7
  hosts: centos_7
  tasks:
    - import_tasks: tasks/gather_packages.yml
    - assert:
        that:
          - "'python' in ansible_facts.packages"
          - "'libselinux-python' in ansible_facts.packages"

- name: Verify python3 on Centos 8
  hosts: centos_8
  tasks:
    - import_tasks: tasks/gather_packages.yml
    - assert:
        that:
          - "'python36' in ansible_facts.packages"
          - "'python3-libselinux' in ansible_facts.packages"

- name: Verify python2 on Debian
  hosts: debian
  tasks:
    - apt:
        name: python-apt
      become: yes
    - import_tasks: tasks/gather_packages.yml
    - assert:
        that:
          - "'python' in ansible_facts.packages"

- name: Verify python3 on Ubuntu
  hosts: ubuntu
  tasks:
    - apt:
        name: python3-apt
      become: yes
    - import_tasks: tasks/gather_packages.yml
    - assert:
        that:
          - "'python3' in ansible_facts.packages"